- name: Import the postgresql apt key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- name: Add postgres APT repository on Ubuntu 18
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main
  when: ansible_facts.distribution_major_version == '18'
- name: Add postgres APT repository on Ubuntu 20
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
  when: ansible_facts.distribution_major_version == '20'
- name: Add postgres APT repository on Ubuntu 20
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main
  when: ansible_facts.distribution_major_version == '22'  
- name: APT install PostgreSQL on Ubuntu
  become: yes
  apt:
    update_cache: yes
    state: present
    name: 
      - "postgresql-{{wanted_postgresql_version}}"
      - python3-psycopg2
      - libpq-dev
  when: ansible_facts.os_family|lower == 'debian'
# - name: Start postgresql
#   become: yes
#   become_user: root
#   ansible.builtin.service:
#     name: postgresql
#     state: restarted
- name: Start postgresql
  become: yes
  become_user: root
  command: service postgresql restart
- name: Get Postgres Version
  become: yes
  become_user: postgres
  command:
    cmd: bash -c "psql --version | awk '{ print $3 }' | awk -F . '{ print $1 }'"
  register: postgres_version
- name: Allow trusted local connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.stdout}}/main/pg_hba.conf
    contype: local
    users: all
    method: trust
- name: Allow trusted local connections for postgres user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.stdout}}/main/pg_hba.conf
    contype: local
    method: trust
    users: postgres
- name: Allow trusted host connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.stdout}}/main/pg_hba.conf
    contype: host
    method: trust
    users: all
    address: all
- name: Allow trusted localhost ipV4 connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.stdout}}/main/pg_hba.conf
    contype: host
    method: trust
    users: all
    address: '127.0.0.1/32'
- name: Allow trusted localhost ipV6 connections
  become: yes
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgres_version.stdout}}/main/pg_hba.conf
    contype: host
    method: trust
    users: all
    address: '::1/128'
- name: Reload postgresql
  become: yes
  become_user: root
  command: service postgresql reload    
# - name: Reload postgresql
#   become: yes
#   become_user: root
#   ansible.builtin.service:
#     name: postgresql
#     state: reloaded
- name: Create postgres user
  become: yes
  become_user: postgres
  become_method: sudo
  community.postgresql.postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER
- name: Create user's default database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ ansible_user_id }}"
- name: Check postgres
  community.postgresql.postgresql_ping:
    login_user: "{{ ansible_user_id }}"
    db: "{{ ansible_user_id }}"
