- name: Install postgresql using homebrew
  community.general.homebrew:
    update_homebrew: yes
    name: "postgresql@{{wanted_postgresql_version}}"
    state: present
- name: Start postgresql
  command: "brew services start postgresql@{{wanted_postgresql_version}}"
- name: Check for default database
  command: "psql {{ ansible_user_id }} -c '\\q'"
  register: default_database
  ignore_errors: yes
- name: Create user's default database
  command: "createdb {{ ansible_user_id }}"
  when: default_database.failed == True
