---
- name: install
  hosts: localhost
  gather_facts: yes
  vars:
    asdf_user: "{{ ansible_user_id }}"
    wanted_postgresql_version: "14"
    wanted_node_version: "16"
  connection: local
  tasks: 
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
        
  roles:
    - zsh
    - ssh-key
    - aliases
    - nodejs
    - postgresql
    - heroku
    - misc-utils
    - python

