---
- name: Install Node {{ wanted_node_version }}
  command:
    cmd: fnm install {{ wanted_node_version }}
    creates:
      - ~/.fnm/node-versions/*{{ wanted_node_version }}*/installation/bin/node
- name: Set Node {{ wanted_node_version }} to be the default
  command:
    cmd: fnm default {{ wanted_node_verion }}
    creates:
      - ~/.fnm/aliases/default
  when: wanted_node_version not in lookup('file', '~/.nvm/alias/default')
- name: Set Node Version Variable
  command:
    cmd: node --version
  register: node_version
- name: Print Node version
  debug:
    msg: "{{ node_version.stdout }}"
