- name: apt upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: full
- name: apt install dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - acl
      - git
      - zip
      - unzip
      - htop
      - curl
      - sl
      - ncdu
      - mc
      - libpq-dev
      - neovim
      - gnupg
- name: Install autojump
  import_tasks: autojump.yml
- name: Install grc
  import_tasks: grc.yml
